language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sinablattmann"
    token:
      secure: "0d2222ac0813f330a416909fb0363b044b065eef"

jdk:
  - openjdk11

script:
  - ./gradlew sonarqube

